name: wakatime-stats

on:
  schedule:
    - cron: "8 * * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update time metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: hud0shnik
          TIME_RANGE: last_30_days
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          COMMIT_MESSAGE: "waka update"
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_UPDATED_DATE: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_TOTAL: "False"
          SHOW_TIME: "False"
          SYMBOL_VERSION: 2
