name: wakatime-stats

on:
  schedule:
    - cron: "0 */8 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update time metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          COMMIT_MESSAGE: "update wakatime metrics"
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_UPDATED_DATE: "False"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE: "True"
          SHOW_COMMIT: "True"
          SYMBOL_VERSION: 2
          SHOW_OS: "True"
